<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
	<PropertyGroup>
		<LangVersion>preview</LangVersion>

		<BuildNumberFile>$(MSBuildProjectDirectory)\BuildNumber.txt</BuildNumberFile>
		<_PreviousBuildNumber Condition="Exists('$(BuildNumberFile)')">$([System.IO.File]::ReadAllText('$(BuildNumberFile)').Trim())</_PreviousBuildNumber>
		<_PreviousBuildNumber Condition="'$(_PreviousBuildNumber)' == ''">0</_PreviousBuildNumber>
		<BuildNumber>$([MSBuild]::Add($(_PreviousBuildNumber), 1))</BuildNumber>
		<VersionPrefix>7.15.0</VersionPrefix>
		<Version>$(VersionPrefix).$(BuildNumber)</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
	</PropertyGroup>

	<Target Name="PersistBuildNumber" AfterTargets="Build">
		<WriteLinesToFile File="$(BuildNumberFile)" Lines="$(BuildNumber)" Overwrite="true" />
	</Target>

	<PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))'">
		<DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ImGuiColorTextEditNetDalamud" Version="1.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
		<PackageReference Include="NLua" Version="1.7.5" />
		<PackageReference Include="Scrutor" Version="6.1.0" />
		<PackageReference Include="YamlDotNet" Version="16.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ECommons\ECommons\ECommons.csproj" />
		<ProjectReference Include="..\AutoRetainerAPI\AutoRetainerAPI\AutoRetainerAPI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="LanguageChineseTraditional.ini" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>